# 🎬 Movie Recommendation System

# Notebook 4: Feature Engineering

## Objective

The objective of this notebook is to prepare textual movie features for the recommendation engine by combining important attributes into a single feature called **tags**.

In [1]:
import pandas as pd
import numpy as np

import re

In [2]:
df = pd.read_csv("../data/processed/movies_cleaned.csv")

df.head()

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,237000000,Action Adventure Fantasy Science Fiction,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,300000000,Adventure Fantasy Action,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,245000000,Action Adventure Crime,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,250000000,Action Crime Drama Thriller,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,260000000,Action Adventure Science Fiction,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [3]:
movies = df[
    [
        "title",
        "genres",
        "keywords",
        "cast",
        "director",
        "overview",
        "vote_average",
        "popularity"
    ]
]

movies.head()

,title,genres,keywords,cast,director,overview,vote_average,popularity
0,Avatar,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron,"In the 22nd century, a paraplegic Marine is di...",7.2,150.437577
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski,"Captain Barbossa, long believed to be dead, ha...",6.9,139.082615
2,Spectre,Action Adventure Crime,spy based on novel secret agent sequel mi6,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,Sam Mendes,A cryptic message from Bond’s past sends him o...,6.3,107.376788
3,The Dark Knight Rises,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan,Following the death of District Attorney Harve...,7.6,112.312950
4,John Carter,Action Adventure Science Fiction,based on novel mars medallion space travel pri...,Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton,"John Carter is a war-weary, former military ca...",6.1,43.926995

In [4]:
movies.isnull().sum()

title           0
genres          0
keywords        0
cast            0
director        0
overview        0
vote_average    0
popularity      0
dtype: int64

In [5]:
text_columns = [
    "genres",
    "keywords",
    "cast",
    "director",
    "overview"
]

movies[text_columns] = movies[text_columns].fillna("")

In [6]:
movies["tags"] = (
    movies["genres"] + " " +
    movies["keywords"] + " " +
    movies["cast"] + " " +
    movies["director"] + " " +
    movies["overview"]
)

In [7]:
movies = movies[
    [
        "title",
        "tags",
        "vote_average",
        "popularity"
    ]
]

movies.head()

,title,tags,vote_average,popularity
0,Avatar,Action Adventure Fantasy Science Fiction cultu...,7.2,150.437577
1,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drug abuse exot...,6.9,139.082615
2,Spectre,Action Adventure Crime spy based on novel secr...,6.3,107.376788
3,The Dark Knight Rises,Action Crime Drama Thriller dc comics crime fi...,7.6,112.312950
4,John Carter,Action Adventure Science Fiction based on nove...,6.1,43.926995

In [8]:
movies["tags"] = movies["tags"].str.lower()

In [9]:
movies["tags"] = movies["tags"].apply(
    lambda x: re.sub(r"[^a-zA-Z0-9 ]", " ", x)
)

In [10]:
movies["tags"] = movies["tags"].str.replace(
    r"\s+",
    " ",
    regex=True
).str.strip()

In [11]:
movies.head()

,title,tags,vote_average,popularity
0,Avatar,action adventure fantasy science fiction cultu...,7.2,150.437577
1,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drug abuse exot...,6.9,139.082615
2,Spectre,action adventure crime spy based on novel secr...,6.3,107.376788
3,The Dark Knight Rises,action crime drama thriller dc comics crime fi...,7.6,112.312950
4,John Carter,action adventure science fiction based on nove...,6.1,43.926995

In [12]:
movies.to_csv(
    "../data/processed/movie_tags.csv",
    index=False
)

print("✅ Feature engineered dataset saved successfully!")

✅ Feature engineered dataset saved successfully!

# Summary

Feature Engineering Completed

The following transformations were performed:

- Selected important recommendation features
- Filled missing textual values
- Combined multiple text columns into a single **tags** feature
- Converted text to lowercase
- Removed punctuation
- Removed unnecessary spaces

The processed dataset is now ready for vectorization and similarity calculation.